# Defined in - @ line 0
function cmds
    echo "tig        - Text-mode interface for git"
    echo "tmux       - Terminal multiplexer"
    echo "fd         - A simple, fast and user-friendly alternative to 'find'"
    echo "fzf        - Fuzzy finder"
    echo "caniuse    - Query caniuse.com"
    echo "emacs      - Text editor"
    echo "rg         - Fast recursive regex search"
    echo "nnn        - Terminal file manager"
    echo "tldr       - Simplified and community-driven man pages"
    echo "cloc       - Counts lines of code"
    echo "glances    - System monitor"
    echo "http       - HTTP client"
    echo "youtube-dl - Video downloader"
    echo "jq         - Sed for JSON"
    echo "bat        - A cat clone with wings"
    echo "pandoc     - Document formatter"
    echo "pgcli      - Postgres CLI"
    echo "mycli      - MySQL CLI"
    echo "ddgr       - Search duckduckgo.com"
    echo "spark      - Sparklines for your shell"
    echo "now        - Free static web publishing"
    echo "loadtest   - Run a load test on a URL"
    echo "pv         - Monitor the progress of data through a pipeline"
    echo "asciinema  - Recordd and share your terminal session"
    echo "fkill      - Kill processes"
end
