(global-set-key "\C-x\C-m" 'execute-extended-command)
(global-set-key "\C-c\C-m" 'execute-extended-command)
(global-set-key "\C-x\C-b" 'ibuffer)
(global-set-key "\C-'" 'iedit-mode-on-function)
(global-set-key "\C-u" 'undo)
(global-set-key "\C-l" 'goto-line)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-cp" 'compile)
(global-set-key "\C-i" 'indent-all)

(global-set-key "\M-i" 'idomenu)
(global-set-key "\M-o" 'occur)
(global-set-key "\M-/" 'hippie-expand)

(global-set-key [f11] 'toggle-fullscreen)
