#!/bin/bash

# Append to the history file rather than overwriting it.
shopt -s histappend

# Increase the history file maximum length and size.
export HISTSIZE=5000
export HISTFILESIZE=10000

# Don't include duplicate commands in the history file.
export HISTCONTROL=ignoredups

# Custom prompt.
export PS1="\[\e[00;37m\]\n[\d \A] [\u@\h] [\w]\n\\$ \[\e[0m\]"

# Use emacs in daemon mode for a quick startup.
export EDITOR='emacsclient -c'

# Startup emacs in --daemon mode if it isn't already.
export ALTERNATE_EDITOR=""

# Custom aliases.
if [ -f $HOME/.dotfiles/bash/bashalias ]; then
    source $HOME/.dotfiles/bash/bashalias
else
    echo "WARNING:  $HOME/.dotfiles/bash/bashalias doesn't exist"
fi

# Custom functions.
if [ -f $HOME/.dotfiles/bash/bashfunction ]; then
    source $HOME/.dotfiles/bash/bashfunction
else
    echo "WARNING:  $HOME/.dotfiles/bash/bashfunction doesn't exist"
fi

# Needed to use the virtualenvwrapper functions.
if [ -f /etc/bash_completion.d/virtualenvwrapper ]; then
    source /etc/bash_completion.d/virtualenvwrapper
else
    echo "WARNING: /etc/bash_completion.d/virtualenvwrapper doesn't exist"
fi
