#!/bin/bash

source ~/.dotfiles/bash/bashfunc
source ~/.dotfiles/bash/bashalias
source ~/.passwords

PS1='\w → '
EDITOR='emacsclient -c'
TERM=xterm-256color

PATH=$PATH:$HOME/bin

# virtualenvwrapper configuration.
WORKON_HOME=/home/gary/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
